name = "club-freedom"

compatibility_date = "2026-04-01"
compatibility_flags = [ "nodejs_compat" ]
main = "@tanstack/react-start/server-entry"

[env.staging]
name = "club-freedom-staging"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
